### ISSUE TITLE
Error writing output file: exit status 1

### ISSUE THREAD

**Issue by nuclearsugar** [CrushedPixel/moshpit#4]
Very cool tool that you're created! Thanks for sharing this. It's very nicely thought through, better than every other tool I've come across.

I'm seeing an error during the "baking output file" stage and the render is halted without outputting the final result. I can see AVI files being written into the TEMP folder, but they are automatically deleted. _(Might be useful to have access to these renders at each stage, maybe as an extra optional argument?)_

I'm running Windows 10 and using the Moshpit binary. I have the latest ffmpeg installed in the system path and confirmed working in other contexts.

**Error:**
`Error writing output file: exit status 1`

**Here is the log from my session:** 
[log.txt](https://github.com/CrushedPixel/moshpit/files/6137692/log.txt)

![2021-03-14 18_13_26-Window](https://user-images.githubusercontent.com/8218211/111086263-8f3c2380-84f1-11eb-807c-868fb9757d29.png)

**Comment by makew0rld** [comment]
Your log indicates this is the same issue as #1. This is fixed in the master branch. I would advise @CrushedPixel to make a new release with binaries, but for now you can download [this](https://github.com/CrushedPixel/moshpit/files/5608092/moshpit.exe.zip). Unzip it and you'll have an EXE that should fix this problem. This is the same binary I provide in #1.

**Comment by nuclearsugar** [comment]
Thanks! That fixed it.
