### ISSUE TITLE
H.264 support

### ISSUE THREAD

**Issue by prldm** [CrushedPixel/moshpit#5]
Make it able to handle natively H.264 (or even H.265) videos, and not reencode them firstly into AVI.

**Comment by makew0rld** [comment]
moshpit supports all video formats. Rencoding to AVI is part of the process and is only a temporary step. H.264 and H.265 support exists.

From the README:

>  moshpit converts the input file into an AVI file, placing I-Frames only at the frames specified by the user. This is done because single frames can be very easily identified and changed in the AVI format.

**Comment by prldm** [comment]
The problem with this is it's not native support. Reencoding into avi produces awful compression artifacts since it is an obsolete codec. Native support would mean that the program would edit and delete I frames directly from the source video (or losslessly copied the video stream), not from a reencoded video.

**Comment by makew0rld** [comment]
Can you give an example of what kind of compression artifacts you experience? The code doesn't necessarily hold the video quality super well, maybe it could be modified with a optional quality flag, that would increase quality at the expense of speed.

But the usage of AVI is intentional. My understanding is that it's easier to datamosh with because of simple I-frame usage. Using H.264 directly for datamoshing is more complicated, if not impossible.

**Comment by CrushedPixel** [comment]
The intermediate conversion to AVI is, as correctly pointed out by @makeworld-the-better-one, essential to how this datamoshing algorithm works. If you're getting compression artifacts, please share some examples with us. It should be pretty easy to tweak the `ffmpeg` arguments to better preserve quality when converting.
